print('Hello')
name = input('What is your name?\n')
print('Hi, %s.' % name)
print('\nI am a bot coded by Abubakr Sultan.')
print('I will ask you some questions.')
food = input('\nWhat is your favourite food?\n')
print('I love to eat %s.' % food)
print ('We have so much in common!')
colour = input('\nWhat is your favourite colour, %s?\n' % name)
print('My favourite colour is also %s. ' % colour)
